from flask import Flask, jsonify, request, send_file
from datetime import datetime
import json
import sqlite3
import qrcode
from io import BytesIO

app = Flask(__name__)

# Deine Bitcoin-Adressen
MY_BITCOIN_ADDRESS = "1EsPPhpa38117tjHbHg5ZmSxJYKAfmC8nt"
ADDITIONAL_ADDRESS = "neumann233@hotmail.de"

def create_withdrawal_code(recipient_address, amount):
    return {
        "transaction_type": "withdrawal",
        "currency": "BTC",
        "amount": amount,
        "recipient": recipient_address,
        "timestamp": datetime.now().isoformat(),
        "status": "pending",
    }

@app.route("/generate_withdrawal_codes", methods=["GET"])
def generate_withdrawal_codes():
    recipient_addresses = [MY_BITCOIN_ADDRESS, ADDITIONAL_ADDRESS]  # Verwende deine Bitcoin-Adressen

    amount = 20.0  # Ändere den Betrag auf 20 BTC

    withdrawal_codes = []
    for address in recipient_addresses:
        withdrawal_code = create_withdrawal_code(address, amount)
        withdrawal_codes.append(withdrawal_code)

    with open("auszahlungscodes.json", "w") as json_file:
        json.dump(withdrawal_codes, json_file, indent=4)

    conn = sqlite3.connect("transaktionen.db")
    try:
        c = conn.cursor()
        c.execute(
            """
            CREATE TABLE IF NOT EXISTS auszahlungen (
                transaction_type TEXT,
                currency TEXT,
                amount REAL,
                recipient TEXT,
                timestamp TEXT,
                status TEXT
            )
            """
        )

        c.executemany(
            """
            INSERT INTO auszahlungen (transaction_type, currency, amount, recipient, timestamp, status)
            VALUES (:transaction_type, :currency, :amount, :recipient, :timestamp, :status)
            """,
            withdrawal_codes,
        )
        conn.commit()
    finally:
        conn.close()

    return jsonify(withdrawal_codes)

@app.route("/view_withdrawal_codes", methods=["GET"])
def view_withdrawal_codes():
    try:
        with open("auszahlungscodes.json", "r") as json_file:
            withdrawal_codes = json.load(json_file)
        return jsonify(withdrawal_codes)
    except FileNotFoundError:
        return jsonify({"error": "Die Datei 'auszahlungscodes.json' wurde nicht gefunden."}), 404

@app.route("/get_latest_transaction", methods=["GET"])
def get_latest_transaction():
    conn = sqlite3.connect("transaktionen.db")
    try:
        c = conn.cursor()
        c.execute("SELECT * FROM auszahlungen ORDER BY timestamp DESC LIMIT 1")
        transaction = c.fetchone()
    finally:
        conn.close()

    if transaction:
        keys = [
            "transaction_type",
            "currency",
            "amount",
            "recipient",
            "timestamp",
            "status",
        ]
        latest_transaction = dict(zip(keys, transaction))
        return jsonify(latest_transaction)
    else:
        return jsonify({"error": "Keine Transaktionen gefunden."}), 404

@app.route("/withdraw", methods=["POST"])
def withdraw():
    data = request.json

    if "amount" not in data:
        return jsonify({"error": "Bitte 'amount' angeben."}), 400

    amount = data["amount"]

    withdrawal_code = create_withdrawal_code(MY_BITCOIN_ADDRESS, amount)

    conn = sqlite3.connect("transaktionen.db")
    try:
        c = conn.cursor()
        # Hier könnte die Logik für die tatsächliche Auszahlung an die Wallet des Empfängers integriert werden
        # Zum Beispiel: bitcoin_api.withdraw(MY_BITCOIN_ADDRESS, amount)

        # Neuen Eintrag in der Datenbank speichern
        c.execute(
            """
            INSERT INTO auszahlungen (transaction_type, currency, amount, recipient, timestamp, status)
            VALUES (:transaction_type, :currency, :amount, :recipient, :timestamp, :status)
            """,
            withdrawal_code,
        )
        conn.commit()
    finally:
        conn.close()

    return jsonify({"message": "Die Auszahlung wurde eingeleitet.", "withdrawal_code": withdrawal_code})

@app.route("/generate_qr_code", methods=["GET"])
def generate_qr_code():
    url = request.args.get('url')
    if not url:
        return jsonify({"error": "URL-Parameter fehlt."}), 400

    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(url)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")
    img_io = BytesIO()
    img.save(img_io, 'PNG')
    img_io.seek(0)

    return send_file(img_io, mimetype='image/png')

if __name__ == "__main__":
    app.run(debug=True)

